spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: server
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LOCAL_MYSQL_HOST}:${LOCAL_MYSQL_PORT}/${MYSQL_DB}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      highlight-sql: true
      ddl-auto: create

      dialect: org.hibernate.dialect.MySQLDialect # ??? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # ?? ?? ??
    generate-ddl: true

  sql:
    init:
      mode: always

